[package]
name = "xerne"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.0", features = ["derive"] }
image = { version = "0.24.6", features = ["rgb", "webp-encoder"] }
